const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
const { pool } = require('../models/db');
exports.signup = async (req,res) => { try { const { email,password,name } = req.body;
const hash = await bcrypt.hash(password,10);
const user = await pool.query('INSERT INTO users(email,password,name) VALUES($1,$2,$3) RETURNING *',[email,hash,name]);
const token = jwt.sign({id:user.rows[0].id},process.env.JWT_SECRET,{expiresIn:'7d'});
res.json({token,user:user.rows[0]}); } catch(err){ console.error(err); res.status(500).json({message:'Signup failed'});} };
exports.login = async(req,res)=>{try{const {email,password}=req.body;
const user = await pool.query('SELECT * FROM users WHERE email=$1',[email]);
if(user.rows.length===0) return res.status(400).json({message:'User not found'});
const valid = await bcrypt.compare(password,user.rows[0].password);
if(!valid) return res.status(400).json({message:'Invalid password'});
const token = jwt.sign({id:user.rows[0].id},process.env.JWT_SECRET,{expiresIn:'7d'});
res.json({token,user:user.rows[0]}); } catch(err){console.error(err); res.status(500).json({message:'Login failed'});} };